
name: HashiCorpDemo_myraprojectrepo_stage
on:
  push:
    branches:
      - main
jobs:
  get-secret:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    name: get-secret
    steps:
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v3.3.0
        with:
          url: https://ra-vault-cluster-public-vault-193294ff.3b9e56d2.z1.hashicorp.cloud:8200
          path: jwt-github-actions
          role: auth.jwt.app1.workflow1_role
          method : jwt
          exportToken: true
          exportEnv: true
          namespace: admin
          secrets: |
            myraproject/data/test secretkey | APPSECRET ;
      - name: Step following 'Import Secrets'
        run: |
          echo '${{ toJson(steps.import-secrets.outputs) }}' > secrets.json
          cat ./secrets.json
          #echo 'For bash'
          APPSECRET="${{ env.APPSECRET }}"
          echo "Stored Output: $APPSECRET"
          #echo 'for windows'         
          #$APPSECRET = "${{ env.APPSECRET }}"
          #echo "Stored Output: $APPSECRET"
